######################
## PYTHON CONTAINER ##
######################
python:
    restart: always
    build: ./app/
    expose:
        - "8001"
    volumes:
        - /usr/src/app
    #dockerfile: Dockerfile
    #command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    command: gunicorn -w 2 -b :8001 app:app

#not using
service:
    restart: always
    build: ./servicio2/
    expose:
        - "8002"
    volumes:
        - /usr/src/app
    dockerfile: Dockerfile
    command: /usr/local/bin/gunicorn -w 2 -b :8002 app:app

     
#####################
## NGINX CONTAINER ##
#####################
nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
    volumes:
        - /www/static
    links:
	- python:python
        - service:service

